# Generated by Django 3.0 on 2019-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing_company', '0001_initial'),
        ('book', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='capa',
            field=models.ImageField(default=1, upload_to='capa', verbose_name='Imagem da capa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_company',
            field=models.ManyToManyField(to='publishing_company.PublishingCompany', verbose_name='Editora'),
        ),
    ]
