# Generated by Django 3.0 on 2020-01-11 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20191216_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='capa',
            new_name='book_cover',
        ),
    ]
