# Generated by Django 3.0.2 on 2020-01-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200111_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='capa/', verbose_name='Imagem da capa'),
        ),
    ]
