# Generated by Django 3.0.3 on 2020-02-22 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200127_0336'),
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='book',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='Livro')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='item',
            field=models.ManyToManyField(to='shopping_cart.Item', verbose_name='Item'),
        ),
    ]
