# Generated by Django 3.0 on 2019-12-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='genre',
        ),
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.ManyToManyField(to='genre.Genre', verbose_name='Gênero'),
        ),
    ]
