# Generated by Django 3.0 on 2020-01-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_auto_20200106_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='descricao',
            field=models.SlugField(unique=True, verbose_name='Descrição'),
        ),
    ]
