# Generated by Django 3.0 on 2020-01-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_auto_20200109_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='link',
            field=models.SlugField(default='Romance', unique=True, verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='descricao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
    ]
